name: Generate HTMLs and upload

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch data and generate
      run: python user.py ${{ secrets.ARGS }}
    - name: Upload HTML
      uses: actions/upload-artifact@v2
      with:
          name: output
          path: opt/*.*
